### ISSUE TITLE
[Updater] System.IO.InvalidDataException: No valid update sources were found.

### ISSUE THREAD

**Issue by JJ0707** [IllusionMods/KKManager#142]
@ManlyMarco 
Some information about the conditions, log following.
Problem occurs while launching the kkmanager / updater via inisettings.

Windows 10
Stable Internet Connection
"Affected" Game: Room Girl (ver R1.4 + English, downloaded from https://lewdgames.net/room-girl-illusion/)
KK Manager Updated manually like in the videos provided: v0.23
No other games in use / installed

**Reproduction with Screen Shots:**
First directly after startup:
![image](https://github.com/IllusionMods/KKManager/assets/149963997/da62d071-d9f9-4729-8bb3-93a79eb7dfb8)

I click apply settings. After a short waiting time:
![image](https://github.com/IllusionMods/KKManager/assets/149963997/7f3ff40f-e1ff-44fc-88e7-caa9848b504c)

Also, he is skipping a lot of Sideloader Modpacks AND tries to connect to hf.honeyselect2 - is this normal? (See log)
The content of my update sources file ist attached right after the log.

**Respective Log**
[19:04:05] Application startup - StandaloneUpdater v0.23.0.0 Amd64
[19:04:05] Following language files are present but they are not specified as supported in LanguageManager: de, fr
[19:04:05] Arguments: O:\RG\Game
[19:04:06] [SelfUpdater] The current version of KKManager is the latest
[19:04:06] Looking for update sources...
[19:04:06] Found 5 sources
[19:04:43] Could not check if running processes have any game files locked because the application is not running as administrator
[19:04:43] Starting update search...
[19:04:43] Start loading zipmods from [O:\RG\Game\mods]
[19:04:43] Finished loading zipmods from [O:\RG\Game\mods] in 193ms
[19:04:44] [eus3.betterrepack.com] Failed to download Updates file Updates1.xml - Failed to download file
[19:04:45] [eus2.betterrepack.com] Failed to download Updates file Updates1.xml - Failed to download file
[19:04:45] [eus3.betterrepack.com] Failed to download Updates file Updates2.xml - Failed to download file
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack KK because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - Bleeding Edge because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - Fixes because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - KK_MaterialEditor because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - KK_UncensorSelector because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - Maps because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - Studio because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - Animations because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping ECSideloader Modpack because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping ECSideloader Modpack UncensorSelector because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping EC Sideloader Modpack Fixes because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISideloader Modpack because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISideloader Modpack - MaterialEditor Shaders because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISideloader Modpack - Uncensor Selector because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISideloader Modpack - Maps because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISideloader Modpack - Studio because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISideloader Modpack - BleedingEdge because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISideloader Modpack - Exclusive because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping HS2Sideloader Modpack - Exclusive because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping KKUserData because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping HS2UserData because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISUserData because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping KKCCP because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping dhh.presets because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping AISideloader Modpack - Game Maps because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping KKSTrial Sideloader Modpack because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - Exclusive KKS because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - KKS_UncensorSelector because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping Sideloader Modpack - KKS_Maps because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping ECSideloader Modpack Old because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping ECSideloader Modpack UncensorSelector old because of conditions
[19:04:45] [eus3.betterrepack.com] Skipping EC Sideloader Modpack Fixes old because of conditions
[19:04:45] [eus2.betterrepack.com] Failed to download Updates file Updates2.xml - Failed to download file
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack KK because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - Bleeding Edge because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - Fixes because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - KK_MaterialEditor because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - KK_UncensorSelector because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - Maps because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - Studio because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - Animations because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping ECSideloader Modpack because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping ECSideloader Modpack UncensorSelector because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping EC Sideloader Modpack Fixes because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISideloader Modpack because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISideloader Modpack - MaterialEditor Shaders because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISideloader Modpack - Uncensor Selector because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISideloader Modpack - Maps because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISideloader Modpack - Studio because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISideloader Modpack - BleedingEdge because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISideloader Modpack - Exclusive because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping HS2Sideloader Modpack - Exclusive because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping KKUserData because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping HS2UserData because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISUserData because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping KKCCP because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping dhh.presets because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping AISideloader Modpack - Game Maps because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping KKSTrial Sideloader Modpack because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - Exclusive KKS because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - KKS_UncensorSelector because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping Sideloader Modpack - KKS_Maps because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping ECSideloader Modpack Old because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping ECSideloader Modpack UncensorSelector old because of conditions
[19:04:45] [eus2.betterrepack.com] Skipping EC Sideloader Modpack Fixes old because of conditions
[19:04:45] [betterrepack.com] Failed to download Updates file Updates2.xml - Failed to download file
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - Exclusive KK and KKS because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack KK because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - Bleeding Edge because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - Fixes because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - KK_MaterialEditor because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - KK_UncensorSelector because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - Maps because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - Studio because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - Animations because of conditions
[19:04:45] [betterrepack.com] Skipping ECSideloader Modpack because of conditions
[19:04:45] [betterrepack.com] Skipping ECSideloader Modpack UncensorSelector because of conditions
[19:04:45] [betterrepack.com] Skipping EC Sideloader Modpack Fixes because of conditions
[19:04:45] [betterrepack.com] Skipping AISideloader Modpack because of conditions
[19:04:45] [betterrepack.com] Skipping AISideloader Modpack - MaterialEditor Shaders because of conditions
[19:04:45] [betterrepack.com] Skipping AISideloader Modpack - Uncensor Selector because of conditions
[19:04:45] [betterrepack.com] Skipping AISideloader Modpack - Maps because of conditions
[19:04:45] [betterrepack.com] Skipping AISideloader Modpack - Studio because of conditions
[19:04:45] [betterrepack.com] Skipping AISideloader Modpack - BleedingEdge because of conditions
[19:04:45] [betterrepack.com] Skipping AISideloader Modpack - Exclusive because of conditions
[19:04:45] [betterrepack.com] Skipping HS2Sideloader Modpack - Exclusive because of conditions
[19:04:45] [betterrepack.com] Skipping HS2UserData because of conditions
[19:04:45] [betterrepack.com] Skipping AISUserData because of conditions
[19:04:45] [betterrepack.com] Skipping KKCCP because of conditions
[19:04:45] [betterrepack.com] Skipping dhh.presets because of conditions
[19:04:45] [betterrepack.com] Skipping AISideloader Modpack - Game Maps because of conditions
[19:04:45] [betterrepack.com] Skipping KKSTrial Sideloader Modpack because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - Exclusive KKS because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - KKS_UncensorSelector because of conditions
[19:04:45] [betterrepack.com] Skipping Sideloader Modpack - KKS_Maps because of conditions
[19:04:45] [betterrepack.com] Skipping ECSideloader Modpack Old because of conditions
[19:04:45] [betterrepack.com] Skipping ECSideloader Modpack UncensorSelector old because of conditions
[19:04:45] [betterrepack.com] Skipping EC Sideloader Modpack Fixes old because of conditions
[19:04:45] [betterrepack.com] Skipping aisr9.1h1 because of conditions
[19:04:45] [betterrepack.com] Skipping kkrx10.h2 because of conditions
[19:04:45] [betterrepack.com] Skipping phr32.h1 because of conditions
[19:04:45] [betterrepack.com] Skipping hs2.401.h because of conditions
[19:04:45] [betterrepack.com] Skipping hs2.5.h because of conditions
[19:04:45] [betterrepack.com] Skipping hs2.5.h.c because of conditions
[19:04:45] [betterrepack.com] Skipping hs2.5.hdhh because of conditions
[19:04:45] [betterrepack.com] Skipping hs2.5.h.cdhh because of conditions
[19:04:45] [betterrepack.com] Skipping kk.101.h because of conditions
[19:04:45] [betterrepack.com] Skipping kkS.1.2.h1 because of conditions
[19:04:45] [betterrepack.com] Skipping HC Cockblocker because of conditions
[19:04:46] [sideload.betterrepack.com] Failed to download Updates file Updates2.xml - Failed to download file
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack KK because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - Bleeding Edge because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - Fixes because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - KK_MaterialEditor because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - KK_UncensorSelector because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - Maps because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - Studio because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - Animations because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping ECSideloader Modpack because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping ECSideloader Modpack UncensorSelector because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping EC Sideloader Modpack Fixes because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISideloader Modpack because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISideloader Modpack - MaterialEditor Shaders because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISideloader Modpack - Uncensor Selector because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISideloader Modpack - Maps because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISideloader Modpack - Studio because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISideloader Modpack - BleedingEdge because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISideloader Modpack - Exclusive because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping HS2Sideloader Modpack - Exclusive because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping KKUserData because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping HS2UserData because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISUserData because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping KKCCP because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping dhh.presets because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping AISideloader Modpack - Game Maps because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping KKSTrial Sideloader Modpack because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - Exclusive KKS because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - KKS_UncensorSelector because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping Sideloader Modpack - KKS_Maps because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping ECSideloader Modpack Old because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping ECSideloader Modpack UncensorSelector old because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping EC Sideloader Modpack Fixes old because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping aisr9.1h1 because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping kkrx10.h2 because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping phr32.h1 because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping hs2.401.h because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping hs2.5.h because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping hs2.5.h.c because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping hs2.5.hdhh because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping hs2.5.h.cdhh because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping kk.101.h because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping kkS.1.2.h1 because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping hs2.r6 because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping hs2.r6ch because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping ais.r11 because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping ais.r11ch because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping kkS.2.h1 because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping kksr2.1h because of conditions
[19:04:46] [sideload.betterrepack.com] Skipping HC Cockblocker because of conditions
[19:04:46] [ERROR] Unexpected error while collecting updates from source hf.honeyselect2.com - skipping the source. Error: System.Net.Sockets.SocketException: Der angegebene Host ist unbekannt
   at IPHostEntry System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at IPAddress[] System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   at async Task FluentFTP.FtpSocketStream.ConnectAsync(string host, int port, FtpIpVersion ipVersions, CancellationToken token)
   at async Task FluentFTP.FtpClient.ConnectAsync(FtpSocketStream stream, CancellationToken token) x 2
   at async Task<List<FtpProfile>> FluentFTP.FtpClient.AutoDetectAsync(bool firstOnly, bool cloneConnection, CancellationToken token) x 2
   at async Task<FtpProfile> FluentFTP.FtpClient.AutoConnectAsync(CancellationToken token)
   at async Task KKManager.Updater.Sources.FtpUpdater.Connect(CancellationToken cancellationToken)+(?) => { } in D:/SVN/KKManager/src/KKManager.Updater/Sources/FtpUpdater.cs:line 185
   at async Task KKManager.Updater.Sources.FtpUpdater.Connect(CancellationToken cancellationToken) in D:/SVN/KKManager/src/KKManager.Updater/Sources/FtpUpdater.cs:line 189
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.FtpUpdater.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/FtpUpdater.cs:line 132
   at async Task KKManager.Updater.UpdateSourceManager+<>c__DisplayClass1_1.<GetUpdates>g__DoUpdate|4(?)+DoUpdate(?) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 71
   at async Task<List<UpdateTask>> KKManager.Updater.UpdateSourceManager.GetUpdates(CancellationToken cancellationToken, UpdateSourceBase[] updateSources, string[] filterByGuids, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 106
[19:04:46] [Updater] Unexpected crash while updating mods, aborting.
[19:04:46] [Updater] System.IO.InvalidDataException: No valid update sources were found. Either the online update source list could not be accessed, your UpdateSources file is corrupted or in an old format, or KK Manager is outdated. Make sure that you are connected to the internet and not behind a firewall (try using a VPN) and check for KK Manager updates.
   at KKManager.Updater.UpdateSourceManager.<GetUpdates>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KKManager.Updater.Windows.ModUpdateProgressDialog.<ModUpdateProgress_Shown>d__9.MoveNext() in D:\SVN\KKManager\src\KKManager.Updater\Windows\ModUpdateProgressDialog.cs:line 214

**Update Sources**
ftp://fvqrybnqre:fvqrybnqre3@rhf2.orggreercnpx.com:2121
ftp://fvqrybnqre:fvqrybnqre3@rhf3.orggreercnpx.com:2121
ftp://fvqrybnqre:fvqrybnqre3@fvqrybnq.orggreercnpx.com:2121
ftp://fvqrybnqre:fvqrybnqre3@orggreercnpx.com:2121
ftp://xxfuner:nlnln@us.ubarlfryrpg2.com:21

**Comment by ManlyMarco** [comment]
Currently there are no update sources available for RoomGirl, this is normal.

**Comment by JJ0707** [comment]
thank you for the quick response!
So that leaves another question for me - I do get the missing zipmod warning at every startup. What could the solution be?

**Comment by ManlyMarco** [comment]
For now you can only download zipmods for RG manually, they are usually found on pixiv, discord, twitter and some Japanese mod sharing websites.
