### ISSUE TITLE
Unhandled exception when selection Basic thumbnail pack v2.2.2.3 in KKManager

### ISSUE THREAD

**Issue by Helblind** [IllusionMods/KKManager#170]
KKManager gives an Unhandled exception error when I select this mod. I have redownloaded it still occurs. Version 2.2.2 does not create this error. The error states you can continue or quit and "Cannot read that as a ZipFile.

When I try to unzip the zipmod I get "File Replace" prompts, asking if I want to replace existing files (eg. 00000000-00000000-_(__).png with 00000000-00000000-?(??).png). Not sure if that is normal.

Perhaps relevant information, this is in the details of the error:

************** Exception Text **************
Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> System.OverflowException: overflow while creating filename
   at Ionic.Zip.ZipEntry.CopyHelper.AppendCopyToFileName(String f)
   at Ionic.Zip.ZipEntry.ReadDirEntry(ZipFile zf, Dictionary`2 previouslySeen)
   at Ionic.Zip.ZipFile.ReadCentralDirectory(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile.Read(Stream zipStream, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress)
   at KKManager.Data.Zipmods.SideloaderModLoader.<>c__DisplayClass9_1.<LoadFromFile>b__4() in D:\SVN\KKManager\src\KKManager.Core\Data\Zipmods\SideloaderModLoader.cs:line 204
   at KKManager.Data.Zipmods.SideloaderModInfo.get_Images() in D:\SVN\KKManager\src\KKManager.Core\Data\Zipmods\SideloaderModInfo.cs:line 58
   at KKManager.Windows.ToolWindows.Properties.Viewers.SideloaderViewerBase.set_CurrentObject(SideloaderModInfo value) in D:\SVN\KKManager\src\KKManager\Windows\ToolWindows\Properties\Viewers\SideloaderViewer.cs:line 30
   at KKManager.Windows.ToolWindows.Properties.PropertiesToolWindow.ShowProperties(Object targetObject, DockContent source) in D:\SVN\KKManager\src\KKManager\Windows\ToolWindows\Properties\PropertiesToolWindow.cs:line 103
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at BrightIdeasSoftware.ObjectListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ManlyMarco** [comment]
Try running in Japanese locale.

**Comment by Helblind** [comment]
Unfortunately, that did not fix the issue.

**Comment by ManlyMarco** [comment]
Does the zipmod load correctly in studio? You should see the thumbnails.

**Comment by Helblind** [comment]
It does seem to load the thumbnails properly. There are a bunch of thumbnails that are questions marks, but less than without the mod loaded.

**Comment by Helblind** [comment]
If I unzip it (selecting auto-rename) then rezip it, it no longer causes the error and seems to work, as far as I can tell.

**Comment by ManlyMarco** [comment]
What compression app and settings did you use to zip it up?

**Comment by Helblind** [comment]
Just 7-zip with default settings: right click add to *.zip.
________________________________

**Comment by ManlyMarco** [comment]
Can confirm that the zipmod in the modpack is messed up, I'll see about fixing it later.

**Comment by Helblind** [comment]
So, I removed the "Misc" folder under the "Sideloader Modpack - Studio" folder and ran an update from KK Manager 1.2.0. It downloaded the KK_QuickAccessBox_Thumbs.zipmod, which gave the same error in KK Manager. Hope that helps!

**Comment by Helblind** [comment]
So, I removed the "Misc" folder under the "Sideloader Modpack - Studio" folder and ran an update from KK Manager 1.2.0. It downloaded the KK_QuickAccessBox_Thumbs.zipmod, which gave the same error in KK Manager. Hope that help!

**Comment by ManlyMarco** [comment]
The zipmod should be fixed in the modpack now.
