### ISSUE TITLE
Can not update mods

### ISSUE THREAD

**Issue by JerryWn12** [IllusionMods/KKManager#172]
log:
```
[14:32:28] Application startup - KKManager v1.2.0.0 Amd64
[14:32:28] Following language files are present but they are not specified as supported in LanguageManager: de, fr
[14:32:29] Game: KoikatsuSunshine   Path: C:\Koikatsu Sunshine
[14:32:29] Start loading zipmods from [C:\Koikatsu Sunshine\mods]
[14:32:29] Start loading plugins from [C:\Koikatsu Sunshine\BepInEx]
[14:32:29] Finished loading plugins from [C:\Koikatsu Sunshine\BepInEx] in 246ms
[14:32:29] Found 1 extended data deserializers
[14:32:29] Finished loading zipmods from [C:\Koikatsu Sunshine\mods] in 503ms
[14:32:31] Looking for update sources...
[14:32:32] Found 5 sources
[14:32:32] Could not check if running processes have any game files locked because the application is not running as administrator
[14:32:32] Temporarily re-enabling mod: C:\Koikatsu Sunshine\BepInEx\plugins\KKS_RimRemover.dl_
[14:32:32] Temporarily re-enabling mod: C:\Koikatsu Sunshine\BepInEx\plugins\KKS_Stiletto.dl_
[14:32:32] Starting update search...
[14:32:34] [hf.honeyselect2.com] Failed to download Updates file Updates.xml - Failed to download file
[14:32:34] [hf.honeyselect2.com] Failed to download Updates file Updates1.xml - Failed to download file
[14:32:34] [hf.honeyselect2.com] Failed to download Updates file Updates2.xml - Failed to download file
[14:32:51] [sideload.betterrepack.com] Failed to download Updates file Updates.xml - Error while downloading the file from the server. See InnerException for more info.
[14:32:52] [eus2.betterrepack.com] Failed to download Updates file Updates.xml - Error while downloading the file from the server. See InnerException for more info.
[14:32:52] [eus3.betterrepack.com] Failed to download Updates file Updates.xml - Error while downloading the file from the server. See InnerException for more info.
[14:32:52] [betterrepack.com] Failed to download Updates file Updates.xml - Error while downloading the file from the server. See InnerException for more info.
[14:32:56] [eus3.betterrepack.com] Failed to download Updates file Updates1.xml - Failed to download file
[14:32:57] [eus3.betterrepack.com] Failed to download Updates file Updates2.xml - Failed to download file
[14:33:09] [sideload.betterrepack.com] Failed to download Updates file Updates1.xml - Error while downloading the file from the server. See InnerException for more info.
[14:33:10] [eus2.betterrepack.com] Failed to download Updates file Updates1.xml - Error while downloading the file from the server. See InnerException for more info.
[14:33:12] [sideload.betterrepack.com] Failed to download Updates file Updates2.xml - Failed to download file
[14:33:12] [betterrepack.com] Failed to download Updates file Updates1.xml - Error while downloading the file from the server. See InnerException for more info.
[14:33:15] [eus2.betterrepack.com] Failed to download Updates file Updates2.xml - Failed to download file
[14:33:15] [ERROR] Unexpected error while collecting updates from source eus2.betterrepack.com - skipping the source. Error: System.IO.FileNotFoundException: [eus2.betterrepack.com] Failed to get update list, check previous log for details.
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.UpdateSourceBase.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/UpdateSourceBase.cs:line 170
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.FtpUpdater.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/FtpUpdater.cs:line 132
   at async Task KKManager.Updater.UpdateSourceManager+<>c__DisplayClass1_1.<GetUpdates>g__DoUpdate|4(?)+DoUpdate(?) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 71
   at async Task<List<UpdateTask>> KKManager.Updater.UpdateSourceManager.GetUpdates(CancellationToken cancellationToken, UpdateSourceBase[] updateSources, string[] filterByGuids, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 106
[14:33:15] [ERROR] Unexpected error while collecting updates from source eus3.betterrepack.com - skipping the source. Error: System.IO.FileNotFoundException: [eus3.betterrepack.com] Failed to get update list, check previous log for details.
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.UpdateSourceBase.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/UpdateSourceBase.cs:line 170
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.FtpUpdater.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/FtpUpdater.cs:line 132
   at async Task KKManager.Updater.UpdateSourceManager+<>c__DisplayClass1_1.<GetUpdates>g__DoUpdate|4(?)+DoUpdate(?) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 71
   at async Task<List<UpdateTask>> KKManager.Updater.UpdateSourceManager.GetUpdates(CancellationToken cancellationToken, UpdateSourceBase[] updateSources, string[] filterByGuids, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 106
[14:33:15] [ERROR] Unexpected error while collecting updates from source sideload.betterrepack.com - skipping the source. Error: System.IO.FileNotFoundException: [sideload.betterrepack.com] Failed to get update list, check previous log for details.
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.UpdateSourceBase.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/UpdateSourceBase.cs:line 170
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.FtpUpdater.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/FtpUpdater.cs:line 132
   at async Task KKManager.Updater.UpdateSourceManager+<>c__DisplayClass1_1.<GetUpdates>g__DoUpdate|4(?)+DoUpdate(?) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 71
   at async Task<List<UpdateTask>> KKManager.Updater.UpdateSourceManager.GetUpdates(CancellationToken cancellationToken, UpdateSourceBase[] updateSources, string[] filterByGuids, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 106
[14:33:17] [betterrepack.com] Failed to download Updates file Updates2.xml - Failed to download file
[14:33:17] [ERROR] Unexpected error while collecting updates from source betterrepack.com - skipping the source. Error: System.IO.FileNotFoundException: [betterrepack.com] Failed to get update list, check previous log for details.
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.UpdateSourceBase.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/UpdateSourceBase.cs:line 170
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.FtpUpdater.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/FtpUpdater.cs:line 132
   at async Task KKManager.Updater.UpdateSourceManager+<>c__DisplayClass1_1.<GetUpdates>g__DoUpdate|4(?)+DoUpdate(?) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 71
   at async Task<List<UpdateTask>> KKManager.Updater.UpdateSourceManager.GetUpdates(CancellationToken cancellationToken, UpdateSourceBase[] updateSources, string[] filterByGuids, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 106
[14:33:17] [ERROR] Unexpected error while collecting updates from source hf.honeyselect2.com - skipping the source. Error: System.IO.FileNotFoundException: [hf.honeyselect2.com] Failed to get update list, check previous log for details.
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.UpdateSourceBase.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/UpdateSourceBase.cs:line 170
   at async Task<List<UpdateTask>> KKManager.Updater.Sources.FtpUpdater.GetUpdateItems(CancellationToken cancellationToken, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/Sources/FtpUpdater.cs:line 132
   at async Task KKManager.Updater.UpdateSourceManager+<>c__DisplayClass1_1.<GetUpdates>g__DoUpdate|4(?)+DoUpdate(?) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 71
   at async Task<List<UpdateTask>> KKManager.Updater.UpdateSourceManager.GetUpdates(CancellationToken cancellationToken, UpdateSourceBase[] updateSources, string[] filterByGuids, bool onlyDiscover, IProgress<float> progressCallback) in D:/SVN/KKManager/src/KKManager.Updater/UpdateSourceManager.cs:line 106
[14:33:17] [Updater] Unexpected crash while updating mods, aborting.
[14:33:17] [Updater] System.IO.InvalidDataException: No valid update sources were found. Either the online update source list could not be accessed, your UpdateSources file is corrupted or in an old format, or KK Manager is outdated. Make sure that you are connected to the internet and not behind a firewall (try using a VPN) and check for KK Manager updates.
   at KKManager.Updater.UpdateSourceManager.<GetUpdates>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KKManager.Updater.Windows.ModUpdateProgressDialog.<ModUpdateProgress_Shown>d__9.MoveNext() in D:\SVN\KKManager\src\KKManager.Updater\Windows\ModUpdateProgressDialog.cs:line 214
[14:33:23] Re-disabling mod: C:\Koikatsu Sunshine\BepInEx\plugins\KKS_RimRemover.dl_
[14:33:23] Re-disabling mod: C:\Koikatsu Sunshine\BepInEx\plugins\KKS_Stiletto.dl_
[14:33:23] Start loading zipmods from [C:\Koikatsu Sunshine\mods]
[14:33:23] Start loading plugins from [C:\Koikatsu Sunshine\BepInEx]
[14:33:23] Finished loading plugins from [C:\Koikatsu Sunshine\BepInEx] in 59ms
[14:33:24] Finished loading zipmods from [C:\Koikatsu Sunshine\mods] in 367ms
```
Normally access [sideload.betterrepack.com](https://sideload.betterrepack.com/) in browser.
Tried enable and disable p2p and proxy for FTP server.
Using latest KKManager release.

**Comment by JerryWn12** [comment]
Normally access https://eus2.betterrepack.com/ in browser too.

**Comment by JerryWn12** [comment]
Solved by turning off proxy.
