### ISSUE TITLE
Cannot download mod updates on Linux, FluentFTP unhandled exception

### ISSUE THREAD

**Issue by OrdinaryMagician** [IllusionMods/KKManager#184]
Any time I start the mod updater, even the standalone version, just a few seconds into searching for updates I get several "unhandled exception" dialogs in a row, followed by a crash once I close them. I'm pasting the log below, doesn't seem like there was a dump or any other files created when this happened, just the log alone.
```
[19:39:34] Application startup - KKManager v1.3.0.0 Amd64
[19:39:34] Following language files are present but they are not specified as supported in LanguageManager: de, fr
[19:39:35] Game: KoikatsuSunshine   Path: H:\KoikatsuSunshine
[19:39:35] Start loading zipmods from [H:\KoikatsuSunshine\mods]
[19:39:35] Start loading plugins from [H:\KoikatsuSunshine\BepInEx]
[19:39:36] Found 1 extended data deserializers
[19:39:40] Finished loading plugins from [H:\KoikatsuSunshine\BepInEx] in 4984ms
[19:39:46] Finished loading zipmods from [H:\KoikatsuSunshine\mods] in 10190ms
[19:40:00] Looking for update sources...
[19:40:01] Found 5 sources
[19:40:02] Starting update search...
[19:40:03] UNHANDLED EXCEPTION: FluentFTP.FtpCommandException: Failed to open file.
   at FluentFTP.FtpClient.<OpenPassiveDataStreamAsync>d__550.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenDataStreamAsync>d__557.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenReadAsync>d__567.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<DownloadFileInternalAsync>d__70.MoveNext()
NBugTrace: Initialized NBug.Settings using the configuration file: H:\KoikatsuSunshine\[UTILITY] KKManager\NBug.config
NBugTrace: Starting to handle a System.AppDomain.UnhandledException.
NBugTrace: Starting to generate a bug report for the exception.
[19:40:03] UNHANDLED EXCEPTION: FluentFTP.FtpCommandException: Failed to open file.
   at FluentFTP.FtpClient.<OpenPassiveDataStreamAsync>d__550.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenDataStreamAsync>d__557.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenReadAsync>d__567.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<DownloadFileInternalAsync>d__70.MoveNext()
NBugTrace: Starting to handle a System.AppDomain.UnhandledException.
NBugTrace: Starting to generate a bug report for the exception.
[19:40:05] UNHANDLED EXCEPTION: FluentFTP.FtpCommandException: Failed to open file.
   at FluentFTP.FtpClient.<OpenPassiveDataStreamAsync>d__550.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenDataStreamAsync>d__557.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenReadAsync>d__567.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<DownloadFileInternalAsync>d__70.MoveNext()
NBugTrace: Starting to handle a System.AppDomain.UnhandledException.
NBugTrace: Starting to generate a bug report for the exception.
[19:40:07] UNHANDLED EXCEPTION: FluentFTP.FtpCommandException: Failed to open file.
   at FluentFTP.FtpClient.<OpenPassiveDataStreamAsync>d__550.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenDataStreamAsync>d__557.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenReadAsync>d__567.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<DownloadFileInternalAsync>d__70.MoveNext()
NBugTrace: Starting to handle a System.AppDomain.UnhandledException.
NBugTrace: Starting to generate a bug report for the exception.
NBugTrace: As per setting 'Settings.StopReportingAfter(30)', bug reporting feature was enabled for a certain amount of time which has now expired: Bug reporting is now disabled.
```

**Comment by OrdinaryMagician** [comment]
The same error is happening even after updating to 1.4.1.

**Comment by ManlyMarco** [comment]
I have no way of testing this so I can't really do much myself to fix this.

**Comment by OrdinaryMagician** [comment]
After updating to wine-staging 9.21 the crash no longer happens. Issue can probably be closed.
