### ISSUE TITLE
Update failed: "An item with the same key has already been added"

### ISSUE THREAD

**Issue by LonelyFrustration** [IllusionMods/KKManager#38]
KKmanager Log: 
[11:58:28] Update search finished. Found 9 update tasks.
[11:59:03] [Updater] Unexpected crash while updating mods, aborting.
[11:59:03] [Updater] System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at KKManager.Updater.Downloader.UpdateDownloadCoordinator.<>c__DisplayClass4_0.<Create>b__4(IGrouping`2 uit)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at KKManager.Updater.Downloader.UpdateDownloadCoordinator.Create(IEnumerable`1 updateTasks)
   at KKManager.Updater.Windows.ModUpdateProgressDialog.<ModUpdateProgress_Shown>d__8.MoveNext()
----------------------------------------------------
I'm not a programer of any kind. Just a user of this mod who doesn't know any other place to ask for a solution. Thanks!

**Comment by ManlyMarco** [comment]
[_build.zip](https://github.com/IllusionMods/KKManager/files/5667768/_build.zip)
Try this build. Extract into your current kkmanager install and replace old files.

**Comment by LonelyFrustration** [comment]
It works! Thankyou.
