### ISSUE TITLE
The interface cannot be displayed and reports an error

### ISSUE THREAD

**Issue by Akoshuailer** [IllusionMods/KKManager#82]
![image](https://user-images.githubusercontent.com/69139162/175197914-1d0d9eb3-7703-4d01-b50c-b72efa863e47.png)
I am using 0.18.0 Click into the taskbar after the icon display but does not show the interface, click Manager again to report an error
 I tried to update to 0.19.0, the update screen can be displayed and successfully updated, restart the computer and open it, but it still does not show, click Manager again and report an error

**Comment by ManlyMarco** [comment]
Send the KKManager.log file.

**Comment by Slender1870** [comment]
I have the same issue (I think), here is my log

[16:11:49] Application startup - KKManager v0.19.0.0 Amd64
[16:11:49] Following language files are present but they are not specified as supported in LanguageManager: de, fr, ja, ru
[16:11:51] Game: Koikatu!   Path: C:\Users\quiri\Downloads\[ScrewThisNoise] Koikatsu BetterRepack R9.2
[16:11:51] Start loading zipmods
[16:11:51] Start loading plugins
[16:11:52] Found 1 extended data deserializers
[16:11:53] Failed to parse card [Male (12).png] with an error: The card is corrupted or in an unknown format
[16:11:54] Failed to parse card [Male (23).png] with an error: The card is corrupted or in an unknown format
[16:11:54] Finished loading plugins
[16:14:23] Failed to load zipmod from "C:\Users\quiri\Downloads\[ScrewThisNoise] Koikatsu BetterRepack R9.2\mods\Sideloader Modpack - Studio\Misc\KK_QuickAccessBox_Thumbs.zipmod" with error: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at KKManager.Data.Zipmods.SideloaderModLoader.<>c.<LoadFromFile>b__9_3(IArchiveEntry x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at KKManager.Data.Zipmods.SideloaderModLoader.LoadFromFile(String filename)
   at KKManager.Data.Zipmods.SideloaderModLoader.<>c__DisplayClass8_0.<TryReadSideloaderMods>g__ReadSideloaderModsAsync|0()
[16:15:02] Finished loading zipmods
[16:15:03] Male (33).png requires zipmods that are missing: yamadamod.eyebrow
[16:15:03] My_Hero_Academia_-_Hado_Nejire_by_Evann.png requires zipmods that are missing: Evaan.NejireHado.Mod

**Comment by ManlyMarco** [comment]
@Slender1870 Nothing in the log should prevent it from working, must be something else.

**Comment by Slender1870** [comment]
I just went ahead and removed all KKmanager files and reinstalled them, it fixed the issue so it might be the case that if you update to V19.0 by replacing the files something goes wrong.

**Comment by ManlyMarco** [comment]
Possibly related to #96
