### ISSUE TITLE
Getting a confusing error message when loading the "Quick Access Box" thumbnails zipmod

### ISSUE THREAD

**Issue by MetalIzanagi** [IllusionMods/KKManager#85]
I keep getting this error message any time I have the quick access thumbnails zipmod downloaded. Unsure what's going on because as far as I can tell there's nothing wrong with the path to the file.

[16:56:56] Failed to load zipmod from "I:\KK Better Repack\mods\Sideloader Modpack - Studio\Misc\KK_QuickAccessBox_Thumbs.zipmod" with error: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at KKManager.Data.Zipmods.SideloaderModLoader.<>c.<LoadFromFile>b__9_3(IArchiveEntry x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at KKManager.Data.Zipmods.SideloaderModLoader.LoadFromFile(String filename)
   at KKManager.Data.Zipmods.SideloaderModLoader.<>c__DisplayClass8_0.<TryReadSideloaderMods>g__ReadSideloaderModsAsync|0()

**Comment by ManlyMarco** [comment]
It might be referring to a path inside of the file. Either way, this is harmless.

**Comment by ManlyMarco** [comment]
This appears to be resolved in latest version.
