### ISSUE TITLE
Error while downloading from server

### ISSUE THREAD

**Issue by QWdfASer** [IllusionMods/KKManager#90]
![image](https://user-images.githubusercontent.com/117020566/198881240-a565f3b9-b197-441e-830e-91bf3040bbdd.png)
When progress reaches 100% it just resets with one of each variant of 1)InnerException, 2)Error while downloading from server, 3)Closed early because of other issues. Keeps cycling and nothing gets downloaded.

**Comment by QWdfASer** [comment]
![image](https://user-images.githubusercontent.com/117020566/198890158-869228d5-ac7d-4e9f-8d51-4ae9d5b50c83.png)
And after 5h "updating".

**Comment by QWdfASer** [comment]
![image](https://user-images.githubusercontent.com/117020566/198904117-5a8b2977-c8f2-471c-a2ae-40da195f56c4.png)
Another 4h and this time it updated nothing.

**Comment by QWdfASer** [comment]
![image](https://user-images.githubusercontent.com/117020566/198904188-3153ca43-bc99-4a18-8f8d-4ff2da4461ba.png)
Updated nothing this time around.

**Comment by QWdfASer** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at KKManager.Updater.Windows.ModUpdateProgressDialog.<>c.<ModUpdateProgress_Shown>b__8_2(Object rowObject)
   at BrightIdeasSoftware.ModelObjectComparer.Compare(Object x, Object y)
   at System.Array.SorterObjectArray.PickPivotAndPartition(Int32 lo, Int32 hi)
   at System.Array.SorterObjectArray.IntroSort(Int32 lo, Int32 hi, Int32 depthLimit)
   at System.Array.SorterObjectArray.IntroSort(Int32 lo, Int32 hi, Int32 depthLimit)
   at System.Array.SorterObjectArray.IntroSort(Int32 lo, Int32 hi, Int32 depthLimit)
   at System.Array.SorterObjectArray.IntroSort(Int32 lo, Int32 hi, Int32 depthLimit)
   at System.Array.SorterObjectArray.IntrospectiveSort(Int32 left, Int32 length)
   --- End of inner exception stack trace ---
   at System.Array.SorterObjectArray.IntrospectiveSort(Int32 left, Int32 length)
   at System.Array.Sort(Array keys, Array items, Int32 index, Int32 length, IComparer comparer)
   at System.Collections.ArrayList.Sort(Int32 index, Int32 count, IComparer comparer)
   at BrightIdeasSoftware.FastObjectListDataSource.Sort(OLVColumn column, SortOrder sortOrder)
   at BrightIdeasSoftware.ObjectListView.DoSort(OLVColumn columnToSort, SortOrder order)
   at BrightIdeasSoftware.ObjectListView.Sort(OLVColumn columnToSort, SortOrder order)
   at KKManager.Updater.Windows.ModUpdateProgressDialog.<>c__DisplayClass8_0.<ModUpdateProgress_Shown>b__8(Object o, EventArgs args)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Bugged out completely and still kept going.
![image](https://user-images.githubusercontent.com/117020566/199537998-48abaea2-d181-4ba5-9102-7c0ae19d6585.png)
